name: test

on:
  schedule:
    - cron: '0 12 * * *'   # 每天中午12点执行一次，按需修改
  workflow_dispatch:       # 支持手动触发

jobs:
  buy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          # Playwright 浏览器安装
          playwright install

      - name: Run test
        env:
          EMAIL: ${{ secrets.EMAIL }}
          PASSWORD: ${{ secrets.PASSWORD }}
          TWOFA: ${{ secrets.TWOFA }}
          URL: ${{ secrets.URL }}
        run: python test.py
